### ISSUE TITLE
[Chore] Split VueJS components

### ISSUE THREAD

**Issue by olivierobert** [mosharaf13/fleet-searcher#32]
## Issue

https://github.com/mosharaf13/fleet-searcher/blob/main/resources/js/components/FleetSearch.vue is a God component as it contains all rendering and presentation logic for the main application. This makes it easy to read and maintain.

## Expected

Extract and separate each UI module into its distinct component.

![image](https://user-images.githubusercontent.com/696529/221097957-dc8a7fc6-7a56-4c66-9b14-4435821a4d14.png)

> **Note**
> Comunication between components can be achieved with $emit (see [docs](https://vuejs.org/guide/components/events.html#events-validation))

**Comment by mosharaf13** [comment]
Yes, splitting the [FleetSearch](https://github.com/mosharaf13/fleetsearcher/blob/main/resources/js/components/FleetSearch.vue) Component into separate components is a chore 😄 that should be regularly performed to make sure my components doesn't become bloated. 

I am planning to split it into three separate components as you suggested. Once I am complete I will create the pull request.
